
services:
  web:
    build: apache
    ports:
      - 80:80
    volumes:
      - ./apache/tarefa1.conf:/etc/apache2/sites-enabled/tarefa1.conf
      - ./exemplo.lan:/opt/web/exemplo.lan
      - ./apache/hosts:/etc/hosts
      - ./apache/tarefa3.conf:/etc/apache2/sites-enabled/tarefa3.conf

    networks:
      redeapache:
        ipv4_address: 192.168.58.11
        aliases:
          - exemplo.lan
          - eq1.exemplo.lan
          - www.exemplo.lan
          - omeusitio.lan
          - www.omeusitio.lan
          
    develop:
      watch:
        - path: ./apache/test1.conf
          action: rebuild

  cliente1:
    image: brunosct/debian12-cliente-firefox
    hostname: cliente1
    networks:
      redeapache:
        ipv4_address: 192.168.58.100
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  cliente2:
    image: brunosct/debian12-cliente-firefox
    hostname: cliente2
    networks:
      redeapache:
        ipv4_address: 192.168.58.130
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix


networks:
  redeapache:
    ipam:
      config:
        - subnet: 192.168.58.0/24